### PR TITLE
allow specify paths with more than 1 segments

### PR DESCRIPTION
**Pull request by velimir**
Example:

``` gherkin
Feature: allow specify full paths
  In order to specify full paths in my features to make requests
  behave-http will need to allow set full paths as well as relative ones

  Scenario Outline: response with appropriate status on incoming requests
    Given I am using server "$TEST_SERVER"
    When I make a GET request to "<path>"
    Then the response status should be <code>

    Examples: good services
    | path                     | code |
    | /good/service            |  200 |
    | /good/service?is_that=ok |  200 |

    Examples: bad services
    | path                     | code |
    | /bad/service             |  404 |
    | /good/service?is_that=no |  503 |
```

### CODE REVIEW

**Comment by velimir** [comment]
partially adresses #1

**Comment by mikek** [comment]
Thanks!

I feel though, if you want to use different base (full) URLs, it might be an indication that you need a separate feature instead.

Also, I am not sure yet what (and if) we can do anything about #1.

**Comment by velimir** [comment]
@mikek I agree with you. It sounds like a different feature, I'll try to find out some new approach for these cases.

**Comment by mikek** [comment]
@velimir0xff note, it's merged nevertheless =)

**Comment by velimir** [comment]
@mikek I know, I'm just interested in this project and going to use it in future, so it's nice to know it's evolving direction :)

**Pull request merged**
